# Generated by Django 5.2.1 on 2025-08-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название игры')),
                ('image', models.ImageField(default='default.jpg', upload_to='game_images', verbose_name='Картинка игры')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='URL-метка')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
            },
        ),
    ]
