# Generated by Django 5.2.1 on 2025-08-28 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='cpu_req',
            field=models.CharField(blank=True, default='0', max_length=200, null=True, verbose_name='Процессор'),
        ),
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание игры'),
        ),
        migrations.AddField(
            model_name='game',
            name='developer',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Разработчик'),
        ),
        migrations.AddField(
            model_name='game',
            name='disk_req',
            field=models.CharField(blank=True, default='0', max_length=50, null=True, verbose_name='Место на жестком диске'),
        ),
        migrations.AddField(
            model_name='game',
            name='edition',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип издания'),
        ),
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.CharField(default=1, max_length=100, verbose_name='Жанр'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='gpu_req',
            field=models.CharField(blank=True, default='0', max_length=200, null=True, verbose_name='Видеокарта'),
        ),
        migrations.AddField(
            model_name='game',
            name='os_req',
            field=models.CharField(blank=True, default='0', max_length=200, null=True, verbose_name='Операционная система'),
        ),
        migrations.AddField(
            model_name='game',
            name='platform',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Платформа'),
        ),
        migrations.AddField(
            model_name='game',
            name='publisher',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Издатель'),
        ),
        migrations.AddField(
            model_name='game',
            name='ram_req',
            field=models.CharField(blank=True, default='0', max_length=200, null=True, verbose_name='Оперативная память'),
        ),
        migrations.AddField(
            model_name='game',
            name='release_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выхода'),
        ),
    ]
