# Generated by Django 5.2.1 on 2025-08-28 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_cpu_req_game_description_game_developer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на видео'),
        ),
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Жанр'),
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='screenshots')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
            ],
            options={
                'verbose_name': 'Скриншот',
                'verbose_name_plural': 'Скриншоты',
            },
        ),
        migrations.AddField(
            model_name='game',
            name='screenshots',
            field=models.ManyToManyField(blank=True, related_name='games', to='games.screenshot', verbose_name='Скриншоты'),
        ),
    ]
