# Generated by Django 5.2.1 on 2025-11-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на видео'),
        ),
    ]
